version: '3.8'
services:
  mysql:
    image: 'mysql:5.7.42-debian'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ruko
      - MYSQL_USER=ruko
      - MYSQL_PASSWORD=ruko
    restart: always
    volumes:
      - 'db-data:/var/lib/mysql'
  webserver:
    image: 'ruko_prod'
    build:
      context: '.'
      target: prod
    ports:
      - '80:80'
    restart: always
volumes:
  db-data: