version: '3.1'
services:
  mysql:
    image: 'mysql:5.7.42-debian'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ruko
      - MYSQL_USER=ruko
      - MYSQL_PASSWORD=ruko
    ports:
      - '8082:3306'
    restart: always
  webserver:
    image: 'ruko_ws'
    build:
      context: '.'
    ports:
      - '8888:80'
    links:
      - mysql