version: '3.8'
services:
  db:
    image: 'mysql:5.7.42-debian'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ruko
      - MYSQL_USER=ruko
      - MYSQL_PASSWORD=ruko
    restart: always
    volumes:
      - 'db-data:/var/lib/mysql'
  webserver:
    user: 'www-data'
    build:
      context: '.'
    restart: always
volumes:
  db-data: {}