version: '3.8'
services:
  webserver:
    image: 'ruko_dev'
    build:
      target: dev
    ports:
      - '8888:80'
    volumes:
      - './app/:/var/www/html/:rw'
      - './xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini'
    extra_hosts:
      - host.docker.internal:host-gateway